# Generated by Django 5.1 on 2024-08-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Image',
            new_name='image',
        ),
    ]
