# Generated by Django 5.1 on 2024-08-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_image_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='properties.city'),
        ),
    ]
